// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"database/sql"
)

type Board struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Column struct {
	ID      int64  `json:"id"`
	BoardID int64  `json:"board_id"`
	Name    string `json:"name"`
	// this is how items will be arranged
	Order    int32        `json:"order"`
	Archived sql.NullTime `json:"archived"`
}

type Item struct {
	ID       int64        `json:"id"`
	ColumnID int64        `json:"column_id"`
	Name     string       `json:"name"`
	Done     sql.NullTime `json:"done"`
}

type Task struct {
	ID     int64        `json:"id"`
	ItemID int64        `json:"item_id"`
	Name   string       `json:"name"`
	Done   sql.NullTime `json:"done"`
}
