// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"context"
)

type Querier interface {
	CreateBoard(ctx context.Context, name string) (Board, error)
	DeleteBoard(ctx context.Context, id int64) (Board, error)
	ListBoards(ctx context.Context, arg ListBoardsParams) ([]Board, error)
	UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error)
}

var _ Querier = (*Queries)(nil)
